name: list_dump_secrets
# List secrets from the APIM code repo (DEV)
on:
  workflow_dispatch:
jobs:
  listdev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: List Dev Secrets
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "dev_secrets.txt"
    
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: DevSecretsVariables
        path: "dev_secrets.txt"
        retention-days: 1

# List secrets from the APIM code repo (TST)
  listtst:
    environment: tst
    runs-on: ubuntu-latest
    steps:
    - name: List Tst Secrets
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "tst_secrets.txt"
     
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: TstSecretsVariables
        path: "tst_secrets.txt"
        retention-days: 1
 
  # List secrets from the APIM code repo (STG)
  liststg:
    environment: stg
    runs-on: ubuntu-latest
    steps:
    - name: List Stg Secrets
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "stg_secrets.txt"

    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: StgSecretsVariables
        path: "stg_secrets.txt"
        retention-days: 1

  # List secrets from the APIM code repo (PRD)
  listprd:
    environment: prd
    runs-on: ubuntu-latest
    steps:
    - name: List Prd Secrets
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "prd_secrets.txt"

    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: PrdSecretsVariables
        path: "prd_secrets.txt"
        retention-days: 1
